<?php

namespace Database\Seeders;

use App\Models\Package;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PackageSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		// Packages' "active" column value
		$appUrl = config('app.url'); // env('APP_URL');
		$isDemoDomain = (isDemoDomain($appUrl) || isDevEnv($appUrl));
		$activeValue = $isDemoDomain ? '1' : '0';
		
		$entries = [
			// promotion
			[
				'type'                  => 'promotion',
				'name'                  => [
					'en' => 'Free',
					'fr' => 'Standard',
					'es' => 'Estándar',
					'ar' => 'اساسي',
					'de' => 'Frei',
					'it' => 'Gratuito',
					'ru' => 'Бесплатно',
					'nl' => 'Vrij',
					'nb' => 'Gratis',
					'uk' => 'безкоштовно',
					'pl' => 'Bezpłatny',
					'ro' => 'Gratuit',
					'el' => 'Δωρεάν',
					'pt' => 'Grátis',
					'da' => 'Gratis',
					'sv' => 'Gratis',
					'fi' => 'Ilmainen',
					'hu' => 'Ingyenes',
					'sr' => 'Бесплатно',
					'cs' => 'Zdarma',
					'bg' => 'Безплатно',
					'hr' => 'Besplatno',
					'et' => 'Tasuta',
					'lt' => 'Nemokamai',
					'lv' => 'Bezmaksas',
					'sk' => 'Zdarma',
					'sl' => 'Brezplačno',
					'is' => 'Ókeypis',
					'sq' => 'Falas',
				],
				'short_name'            => [
					'en' => 'Free',
					'fr' => 'Standard',
					'es' => 'Estándar',
					'ar' => 'اساسي',
					'de' => 'Frei',
					'it' => 'Gratuito',
					'ru' => 'Бесплатно',
					'nl' => 'Vrij',
					'nb' => 'Gratis',
					'uk' => 'безкоштовно',
					'pl' => 'Bezpłatny',
					'ro' => 'Gratuit',
					'el' => 'Δωρεάν',
					'pt' => 'Grátis',
					'da' => 'Gratis',
					'sv' => 'Gratis',
					'fi' => 'Ilmainen',
					'hu' => 'Ingyenes',
					'sr' => 'Бесплатно',
					'cs' => 'Zdarma',
					'bg' => 'Безплатно',
					'hr' => 'Besplatno',
					'et' => 'Tasuta',
					'lt' => 'Nemokamai',
					'lv' => 'Bezmaksas',
					'sk' => 'Zdarma',
					'sl' => 'Brezplačno',
					'is' => 'Ókeypis',
					'sq' => 'Falas',
				],
				'ribbon'                => null,
				'has_badge'             => '0',
				'price'                 => '0.00',
				'currency_code'         => 'USD',
				'promotion_time'        => null,
				'expiration_time'       => null,
				'description'           => null,
				'facebook_ads_duration' => '0',
				'google_ads_duration'   => '0',
				'twitter_ads_duration'  => '0',
				'linkedin_ads_duration' => '0',
				'recommended'           => '0',
				'parent_id'             => null,
				'lft'                   => '2',
				'rgt'                   => '3',
				'depth'                 => '0',
				'active'                => $activeValue,
			],
			[
				'type'                  => 'promotion',
				'name'                  => [
					'en' => 'Premium Listing',
					'fr' => 'Annonce Premium',
					'es' => 'Anuncio premium',
					'ar' => 'إعلان مميز',
					'de' => 'Premium Eintrag',
					'it' => 'Inserzione Premium',
					'ru' => 'Премиум-листинг',
					'nl' => 'Premium-vermelding',
					'nb' => 'Premium-oppføring',
					'uk' => 'Преміум лістинг',
					'pl' => 'Wpis Premium',
					'ro' => 'Listare Premium',
					'el' => 'Καταχώριση Premium',
					'pt' => 'Listagem Premium',
					'da' => 'Premium Listing',
					'sv' => 'Premium Listning',
					'fi' => 'Premium-listaus',
					'hu' => 'Prémium hirdetés',
					'sr' => 'Премиум листинг',
					'cs' => 'Premium seznam',
					'bg' => 'Премиум листинг',
					'hr' => 'Premium oglas',
					'et' => 'Premium loend',
					'lt' => 'Premium sąrašas',
					'lv' => 'Premium saraksts',
					'sk' => 'Premium zoznam',
					'sl' => 'Premium seznam',
					'is' => 'Premium skráning',
					'sq' => 'Listimi Premium',
				],
				'short_name'            => [
					'en' => 'Premium',
					'fr' => 'Premium',
					'es' => 'Prima',
					'ar' => 'الممتازة',
					'de' => 'Premium',
					'it' => 'Premio',
					'ru' => 'Премиум',
					'nl' => 'Premie',
					'nb' => 'Premium',
					'uk' => 'Преміум',
					'pl' => 'Premia',
					'ro' => 'Premium',
					'el' => 'Ασφάλιστρο',
					'pt' => 'Premium',
					'da' => 'Premium',
					'sv' => 'Premium',
					'fi' => 'Premium',
					'hu' => 'Prémium',
					'sr' => 'Премиум',
					'cs' => 'Premium',
					'bg' => 'Премиум',
					'hr' => 'Premium',
					'et' => 'Premium',
					'lt' => 'Premium',
					'lv' => 'Premium',
					'sk' => 'Premium',
					'sl' => 'Premium',
					'is' => 'Premium',
					'sq' => 'Premium',
				],
				'ribbon'                => null,
				'has_badge'             => '0',
				'price'                 => '99.00',
				'currency_code'         => 'USD',
				'promotion_time'        => '7',
				'expiration_time'       => '60',
				'description'           => [
					'en' => "Featured on the Homepage\nFeatured in the Category",
					'fr' => "En vedette à l'accueil\nEn vedette dans la catégorie",
					'es' => "Destacado en la página de inicio\nDestacado en la categoría",
					'ar' => "ظهرت في الاستقبال\nظهرت في الفئة",
					'de' => "Auf der Homepage vorgestellt\nIn der Kategorie vorgestellt",
					'it' => "In evidenza nella homepage\nIn evidenza nella categoria",
					'ru' => "Представлено на главной странице\nПредставлено в категории",
					'nl' => "Uitgelicht op de homepage\nUitgelicht in de categorie",
					'nb' => "Fremhevet på hjemmesiden\nUtvalgt i kategorien",
					'uk' => "Показано на домашній сторінці\nПоказано в категорії",
					'pl' => "Polecane na stronie głównej\nPolecane w kategorii",
					'ro' => "Prezentat pe pagina de pornire\nPrezentat în categorie",
					'el' => "Εμφανίζεται στην αρχική σελίδα\nΠροβάλλεται στην κατηγορία",
					'pt' => "Em destaque na página inicial\nEm destaque na categoria",
					'da' => "Fremhævet på hjemmesiden\nFremhævet i kategorien",
					'sv' => "Utvald på hemsidan\nUtvald i kategorin",
					'fi' => "Esitelty etusivulla\nEsitelty kategoriassa",
					'hu' => "Kiemelve a főoldalon\nKiemelve a kategóriában",
					'sr' => "Istaknuto na početnoj stranici\nIstaknuto u kategoriji",
					'cs' => "Zobrazeno na domovské stránce\nZobrazeno v kategorii",
					'bg' => "Избрано на началната страница\nИзбрано в категорията",
					'hr' => "Istaknuto na početnoj stranici\nIstaknuto u kategoriji",
					'et' => "Esiletõstetud avalehel\nEsiletõstetud kategoorias",
					'lt' => "Išryškinta pagrindiniame puslapyje\nIšryškinta kategorijoje",
					'lv' => "Izcelts sākumlapā\nIzcelts kategorijā",
					'sk' => "Zobrazené na domovskej stránke\nZobrazené v kategórii",
					'sl' => "Izpostavljeno na domači strani\nIzpostavljeno v kategoriji",
					'is' => "Uppfærður á forsíðu\nUppfærður í flokknum",
					'sq' => "Të paraqitura në faqen kryesore\nTë paraqitura në kategorinë",
				],
				'facebook_ads_duration' => '0',
				'google_ads_duration'   => '0',
				'twitter_ads_duration'  => '0',
				'linkedin_ads_duration' => '0',
				'recommended'           => '1',
				'parent_id'             => null,
				'lft'                   => '4',
				'rgt'                   => '5',
				'depth'                 => '0',
				'active'                => $activeValue,
			],
			[
				'type'                  => 'promotion',
				'name'                  => [
					'en' => 'Premium Listing (+)',
					'fr' => 'Annonce Premium (+)',
					'es' => 'Anuncio premium (+)',
					'ar' => 'إعلان مميز (+)',
					'de' => 'Premium-Listung (+)',
					'it' => 'Inserzione Premio (+)',
					'ru' => 'Премиум-листинг (+)',
					'nl' => 'Premium vermelding (+)',
					'nb' => 'Premium-oppføring (+)',
					'uk' => 'Преміум лістинг (+)',
					'pl' => 'Wpis Premium (+)',
					'ro' => 'Listare premium (+)',
					'el' => 'Καταχώριση Premium (+)',
					'pt' => 'Listagem Premium (+)',
					'da' => 'Premium Listing (+)',
					'sv' => 'Premium Listning (+)',
					'fi' => 'Premium-listaus (+)',
					'hu' => 'Prémium hirdetés (+)',
					'sr' => 'Премиум листинг (+)',
					'cs' => 'Premium seznam (+)',
					'bg' => 'Премиум листинг (+)',
					'hr' => 'Premium oglas (+)',
					'et' => 'Premium loend (+)',
					'lt' => 'Premium sąrašas (+)',
					'lv' => 'Premium saraksts (+)',
					'sk' => 'Premium zoznam (+)',
					'sl' => 'Premium seznam (+)',
					'is' => 'Premium skráning (+)',
					'sq' => 'Listimi Premium (+)',
				],
				'short_name'            => [
					'en' => 'Premium+',
					'fr' => 'Premium+',
					'es' => 'Prima+',
					'ar' => 'الممتازة+',
					'de' => 'Premium+',
					'it' => 'Premio+',
					'ru' => 'Премиум+',
					'nl' => 'Premie+',
					'nb' => 'Premium+',
					'uk' => 'Преміум+',
					'pl' => 'Premium+',
					'ro' => 'Premium+',
					'el' => 'Ασφάλιστρο+',
					'pt' => 'Premium+',
					'da' => 'Premium+',
					'sv' => 'Premium+',
					'fi' => 'Premium+',
					'hu' => 'Prémium+',
					'sr' => 'Премиум+',
					'cs' => 'Premium+',
					'bg' => 'Премиум+',
					'hr' => 'Premium+',
					'et' => 'Premium+',
					'lt' => 'Premium+',
					'lv' => 'Premium+',
					'sk' => 'Premium+',
					'sl' => 'Premium+',
					'is' => 'Premium+',
					'sq' => 'Premium+',
				],
				'ribbon'                => null,
				'has_badge'             => '0',
				'price'                 => '129.00',
				'currency_code'         => 'USD',
				'promotion_time'        => '30',
				'expiration_time'       => '120',
				'description'           => [
					'en' => "Featured on the Homepage\nFeatured in the Category",
					'fr' => "En vedette à l'accueil\nEn vedette dans la catégorie",
					'es' => "Destacado en la página de inicio\nDestacado en la categoría",
					'ar' => "ظهرت في الاستقبال\nظهرت في الفئة",
					'de' => "Auf der Homepage vorgestellt\nIn der Kategorie vorgestellt",
					'it' => "In evidenza nella homepage\nIn evidenza nella categoria",
					'ru' => "Представлено на главной странице\nПредставлено в категории",
					'nl' => "Uitgelicht op de homepage\nUitgelicht in de categorie",
					'nb' => "Fremhevet på hjemmesiden\nUtvalgt i kategorien",
					'uk' => "Показано на домашній сторінці\nПоказано в категорії",
					'pl' => "Polecane na stronie głównej\nPolecane w kategorii",
					'ro' => "Prezentat pe pagina de pornire\nPrezentat în categorie",
					'el' => "Εμφανίζεται στην αρχική σελίδα\nΠροβάλλεται στην κατηγορία",
					'pt' => "Em destaque na página inicial\nEm destaque na categoria",
					'da' => "Fremhævet på hjemmesiden\nFremhævet i kategorien",
					'sv' => "Utvald på hemsidan\nUtvald i kategorin",
					'fi' => "Esitelty etusivulla\nEsitelty kategoriassa",
					'hu' => "Kiemelve a főoldalon\nKiemelve a kategóriában",
					'sr' => "Istaknuto na početnoj stranici\nIstaknuto u kategoriji",
					'cs' => "Zobrazeno na domovské stránce\nZobrazeno v kategorii",
					'bg' => "Избрано на началната страница\nИзбрано в категорията",
					'hr' => "Istaknuto na početnoj stranici\nIstaknuto u kategoriji",
					'et' => "Esiletõstetud avalehel\nEsiletõstetud kategoorias",
					'lt' => "Išryškinta pagrindiniame puslapyje\nIšryškinta kategorijoje",
					'lv' => "Izcelts sākumlapā\nIzcelts kategorijā",
					'sk' => "Zobrazené na domovskej stránke\nZobrazené v kategórii",
					'sl' => "Izpostavljeno na domači strani\nIzpostavljeno v kategoriji",
					'is' => "Uppfærður á forsíðu\nUppfærður í flokknum",
					'sq' => "Të paraqitura në faqen kryesore\nTë paraqitura në kategorinë",
				],
				'facebook_ads_duration' => '0',
				'google_ads_duration'   => '0',
				'twitter_ads_duration'  => '0',
				'linkedin_ads_duration' => '0',
				'recommended'           => '0',
				'parent_id'             => null,
				'lft'                   => '6',
				'rgt'                   => '7',
				'depth'                 => '0',
				'active'                => $activeValue,
			],
			// subscription
			[
				'type'            => 'subscription',
				'name'            => [
					'en' => 'Basic',
					'fr' => 'Basique',
					'es' => 'Básico',
					'ar' => 'أساسي',
					'de' => 'Basic',
					'it' => 'Di base',
					'ru' => 'Базовый',
					'nl' => 'Basis',
					'nb' => 'Grunnleggende',
					'uk' => 'Базовий',
					'pl' => 'Podstawowy',
					'ro' => 'De bază',
					'el' => 'Βασικός',
					'pt' => 'Básico',
					'da' => 'Basis',
					'sv' => 'Grundläggande',
					'fi' => 'Perus',
					'hu' => 'Alap',
					'sr' => 'Основни',
					'cs' => 'Základní',
					'bg' => 'Основен',
					'hr' => 'Osnovni',
					'et' => 'Põhi',
					'lt' => 'Pagrindinis',
					'lv' => 'Pamata',
					'sk' => 'Základný',
					'sl' => 'Osnovni',
					'is' => 'Grunnur',
					'sq' => 'Bazik',
				],
				'short_name'      => [
					'en' => 'Basic',
					'fr' => 'Basique',
					'es' => 'Básico',
					'ar' => 'أساسي',
					'de' => 'Basic',
					'it' => 'Di base',
					'ru' => 'Базовый',
					'nl' => 'Basis',
					'nb' => 'Grunnleggende',
					'uk' => 'Базовий',
					'pl' => 'Podstawowy',
					'ro' => 'De bază',
					'el' => 'Βασικός',
					'pt' => 'Básico',
					'da' => 'Basis',
					'sv' => 'Grundläggande',
					'fi' => 'Perus',
					'hu' => 'Alap',
					'sr' => 'Основни',
					'cs' => 'Základní',
					'bg' => 'Основен',
					'hr' => 'Osnovni',
					'et' => 'Põhi',
					'lt' => 'Pagrindinis',
					'lv' => 'Pamata',
					'sk' => 'Základný',
					'sl' => 'Osnovni',
					'is' => 'Grunnur',
					'sq' => 'Bazik',
				],
				'price'           => '0.00',
				'currency_code'   => 'USD',
				'interval'        => 'month', // week, month, year or null
				'listings_limit'  => null,
				'expiration_time' => null,
				'description'     => null,
				'recommended'     => '0',
				'parent_id'       => null,
				'lft'             => '8',
				'rgt'             => '9',
				'depth'           => '0',
				'active'          => $activeValue,
			],
			[
				'type'            => 'subscription',
				'name'            => [
					'en' => 'Premium',
					'fr' => 'Premium',
					'es' => 'Prima',
					'ar' => 'الممتازة',
					'de' => 'Premium',
					'it' => 'Premio',
					'ru' => 'Премиум',
					'nl' => 'Premie',
					'nb' => 'Premium',
					'uk' => 'Преміум',
					'pl' => 'Premia',
					'ro' => 'Premium',
					'el' => 'Ασφάλιστρο',
					'pt' => 'Premium',
					'da' => 'Premium',
					'sv' => 'Premium',
					'fi' => 'Premium',
					'hu' => 'Prémium',
					'sr' => 'Премиум',
					'cs' => 'Premium',
					'bg' => 'Премиум',
					'hr' => 'Premium',
					'et' => 'Premium',
					'lt' => 'Premium',
					'lv' => 'Premium',
					'sk' => 'Premium',
					'sl' => 'Premium',
					'is' => 'Premium',
					'sq' => 'Premium',
				],
				'short_name'      => [
					'en' => 'Premium',
					'fr' => 'Premium',
					'es' => 'Prima',
					'ar' => 'الممتازة',
					'de' => 'Premium',
					'it' => 'Premio',
					'ru' => 'Премиум',
					'nl' => 'Premie',
					'nb' => 'Premium',
					'uk' => 'Преміум',
					'pl' => 'Premia',
					'ro' => 'Premium',
					'el' => 'Ασφάλιστρο',
					'pt' => 'Premium',
					'da' => 'Premium',
					'sv' => 'Premium',
					'fi' => 'Premium',
					'hu' => 'Prémium',
					'sr' => 'Премиум',
					'cs' => 'Premium',
					'bg' => 'Премиум',
					'hr' => 'Premium',
					'et' => 'Premium',
					'lt' => 'Premium',
					'lv' => 'Premium',
					'sk' => 'Premium',
					'sl' => 'Premium',
					'is' => 'Premium',
					'sq' => 'Premium',
				],
				'price'           => '9.00',
				'currency_code'   => 'USD',
				'interval'        => 'month', // week, month, year or null
				'listings_limit'  => '100',
				'expiration_time' => '90',
				'description'     => null,
				'recommended'     => '1',
				'parent_id'       => null,
				'lft'             => '10',
				'rgt'             => '11',
				'depth'           => '0',
				'active'          => $activeValue,
			],
		];
		
		$tableName = (new Package())->getTable();
		foreach ($entries as $entry) {
			$entry = arrayTranslationsToJson($entry);
			$entryId = DB::table($tableName)->insertGetId($entry);
		}
	}
}
