<?php

namespace Database\Seeders;

use App\Models\PostType;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PostTypeSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		$entries = [
			[
				'name'   => [
					'en' => 'Full-time',
					'fr' => 'Plein temps',
					'es' => 'Tiempo completo',
					'ar' => 'وقت كامل',
					'de' => 'Vollzeit',
					'it' => 'A tempo pieno',
					'ru' => 'На постоянной основе',
					'nl' => 'Voltijds',
					'nb' => 'Heltid',
					'uk' => 'Повний робочий день',
					'pl' => 'Pełny etat',
					'ro' => 'Cu normă întreagă',
					'el' => 'Πλήρης απασχόληση',
					'pt' => 'Tempo integral',
					'da' => 'Fuldtid',
					'sv' => 'Heltid',
					'fi' => 'Kokopäivätyö',
					'hu' => 'Teljes munkaidő',
					'sr' => 'Пуно радно време',
					'cs' => 'Plný úvazek',
					'bg' => 'Пълен работен ден',
					'hr' => 'Puno radno vrijeme',
					'et' => 'Täistööaeg',
					'lt' => 'Visas darbo laikas',
					'lv' => 'Pilna slodze',
					'sk' => 'Plný úväzok',
					'sl' => 'Polni delovni čas',
					'is' => 'Fullt starf',
					'sq' => 'Me kohë të plotë',
				],
				'lft'    => null,
				'rgt'    => null,
				'depth'  => null,
				'active' => '1',
			],
			[
				'name'   => [
					'en' => 'Part-time',
					'fr' => 'Temps partiel',
					'es' => 'Tiempo parcial',
					'ar' => 'دوام جزئى',
					'de' => 'Teilzeit',
					'it' => 'Part-time',
					'ru' => 'Неполная занятость',
					'nl' => 'Deeltijd',
					'nb' => 'Deltid',
					'uk' => 'Неповний робочий день',
					'pl' => 'Niepełny etat',
					'ro' => 'Cu jumătate de normă',
					'el' => 'Μερική απασχόληση',
					'pt' => 'Meio período',
					'da' => 'Deltid',
					'sv' => 'Deltid',
					'fi' => 'Osa-aikatyö',
					'hu' => 'Részmunkaidő',
					'sr' => 'Пола радног времена',
					'cs' => 'Částečný úvazek',
					'bg' => 'Непълно работно време',
					'hr' => 'Nepuno radno vrijeme',
					'et' => 'Osaline tööaeg',
					'lt' => 'Nepilnas darbo laikas',
					'lv' => 'Nepilna slodze',
					'sk' => 'Čiastočný úväzok',
					'sl' => 'Nepolni delovni čas',
					'is' => 'Hlutastarf',
					'sq' => 'Me kohë të pjesshme',
				],
				'lft'    => null,
				'rgt'    => null,
				'depth'  => null,
				'active' => '1',
			],
			[
				'name'   => [
					'en' => 'Temporary',
					'fr' => 'Temporaire',
					'es' => 'Temporal',
					'ar' => 'مؤقت',
					'de' => 'Vorübergehend',
					'it' => 'Temporaneo',
					'ru' => 'Временный',
					'nl' => 'Tijdelijk',
					'nb' => 'Midlertidig',
					'uk' => 'Тимчасовий',
					'pl' => 'Tymczasowy',
					'ro' => 'Temporar',
					'el' => 'Προσωρινός',
					'pt' => 'Temporário',
					'da' => 'Midlertidig',
					'sv' => 'Tillfällig',
					'fi' => 'Väliaikainen',
					'hu' => 'Ideiglenes',
					'sr' => 'Привремено',
					'cs' => 'Dočasný',
					'bg' => 'Временен',
					'hr' => 'Privremen',
					'et' => 'Ajutine',
					'lt' => 'Laikinas',
					'lv' => 'Pagaidu',
					'sk' => 'Dočasný',
					'sl' => 'Začasni',
					'is' => 'Tímabundið',
					'sq' => 'I përkohshëm',
				],
				'lft'    => null,
				'rgt'    => null,
				'depth'  => null,
				'active' => '1',
			],
			[
				'name'   => [
					'en' => 'Contract',
					'fr' => 'Contract',
					'es' => 'Contract',
					'ar' => 'عقد',
					'de' => 'Vertrag',
					'it' => 'Contrarre',
					'ru' => 'Договор',
					'nl' => 'Contract',
					'nb' => 'Kontrakt',
					'uk' => 'Договір',
					'pl' => 'Umowa',
					'ro' => 'Contracta',
					'el' => 'Σύμβαση',
					'pt' => 'Contrato',
					'da' => 'Kontrakt',
					'sv' => 'Kontrakt',
					'fi' => 'Sopimus',
					'hu' => 'Szerződés',
					'sr' => 'Уговор',
					'cs' => 'Smlouva',
					'bg' => 'Договор',
					'hr' => 'Ugovor',
					'et' => 'Leping',
					'lt' => 'Sutartis',
					'lv' => 'Līgums',
					'sk' => 'Zmluva',
					'sl' => 'Pogodba',
					'is' => 'Samningur',
					'sq' => 'Kontratë',
				],
				'lft'    => null,
				'rgt'    => null,
				'depth'  => null,
				'active' => '1',
			],
			[
				'name'   => [
					'en' => 'Internship',
					'fr' => 'Stage',
					'es' => 'Internado',
					'ar' => 'فترة تدريب',
					'de' => 'Praktikum',
					'it' => 'Tirocinio',
					'ru' => 'Стажировка',
					'nl' => 'Stage',
					'nb' => 'Internship',
					'uk' => 'Інтернатура',
					'pl' => 'Staż',
					'ro' => 'Stagiu',
					'el' => 'Πρακτική άσκηση',
					'pt' => 'Estágio',
					'da' => 'Praktikophold',
					'sv' => 'Praktikplats',
					'fi' => 'Harjoittelu',
					'hu' => 'Gyakornoki pozíció',
					'sr' => 'Стажирање',
					'cs' => 'Stáž',
					'bg' => 'Стаж',
					'hr' => 'Pripravništvo',
					'et' => 'Praktika',
					'lt' => 'Praktika',
					'lv' => 'Prakse',
					'sk' => 'Stáž',
					'sl' => 'Pripravništvo',
					'is' => 'Starfsnám',
					'sq' => 'Praktikë',
				],
				'lft'    => null,
				'rgt'    => null,
				'depth'  => null,
				'active' => '1',
			],
			[
				'name'   => [
					'en' => 'Permanent',
					'fr' => 'Permanent',
					'es' => 'Permanente',
					'ar' => 'دائم',
					'de' => 'Dauerhaft',
					'it' => 'Permanente',
					'ru' => 'Постоянный',
					'nl' => 'Permanent',
					'nb' => 'Fast',
					'uk' => 'Постійний',
					'pl' => 'Stały',
					'ro' => 'Permanent',
					'el' => 'Μόνιμος',
					'pt' => 'Permanente',
					'da' => 'Permanent',
					'sv' => 'Permanent',
					'fi' => 'Pysyvä',
					'hu' => 'Állandó',
					'sr' => 'Трајан',
					'cs' => 'Trvalý',
					'bg' => 'Постоянен',
					'hr' => 'Stalan',
					'et' => 'Püsiv',
					'lt' => 'Nuolatinis',
					'lv' => 'Pastāvīgs',
					'sk' => 'Trvalý',
					'sl' => 'Trajni',
					'is' => 'Varanlegur',
					'sq' => 'I përhershëm',
				],
				'lft'    => null,
				'rgt'    => null,
				'depth'  => null,
				'active' => '1',
			],
			[
				'name'   => [
					'en' => 'Optional',
					'fr' => 'Optional',
					'es' => 'Opcional',
					'ar' => 'اختياري',
					'de' => 'Optional',
					'it' => 'Opzionale',
					'ru' => 'Необязательный',
					'nl' => 'Optioneel',
					'nb' => 'Valgfri',
					'uk' => 'Додатково',
					'pl' => 'Fakultatywny',
					'ro' => 'Opțional',
					'el' => 'Προαιρετικός',
					'pt' => 'Opcional',
					'da' => 'Valgfri',
					'sv' => 'Valfri',
					'fi' => 'Valinnainen',
					'hu' => 'Választható',
					'sr' => 'Опционо',
					'cs' => 'Volitelný',
					'bg' => 'Избираем',
					'hr' => 'Opcionalan',
					'et' => 'Valikuline',
					'lt' => 'Pasirenkamas',
					'lv' => 'Pēc izvēles',
					'sk' => 'Voliteľný',
					'sl' => 'Izbirni',
					'is' => 'Valfrjáls',
					'sq' => 'Opsional',
				],
				'lft'    => null,
				'rgt'    => null,
				'depth'  => null,
				'active' => '1',
			],
		];
		
		$tableName = (new PostType())->getTable();
		foreach ($entries as $entry) {
			$entry = arrayTranslationsToJson($entry);
			$entryId = DB::table($tableName)->insertGetId($entry);
		}
	}
}
